Django_project/api/urls.py
from .views import (
    CategoryListView, CarListView, CarDetailView, CarCreateView, CarUpdateView, CarDeleteView,
    CarListCreateView, CarRetrieveUpdateDeleteView,
    CarViewSet
)
from rest_framework.routers import DefaultRouter
from django.urls import path, include

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)


router = DefaultRouter()

router.register('cars', CarViewSet, basename='cars')

app_name = 'api'

urlpatterns = [
    path('categories/', CategoryListView.as_view(), name='category_list'),
    # path('cars/', CarListView.as_view(), name='car_list'),
    # path('cars/create/', CarCreateView.as_view(), name='car_create'),
    # path('cars/<int:id>/', CarDetailView.as_view(), name='car_details'),
    # path('cars/update/<int:pk>/', CarUpdateView.as_view(), name='car_update'),
    # path('cars/delete/<int:pk>/', CarDeleteView.as_view(), name='car_delete'),
    # path('cars/', CarListCreateView.as_view(), name='car_list_create'),
    # path('cars/<int:pk>/', CarRetrieveUpdateDeleteView.as_view(), name='car_detail'),
    path('', include(router.urls)),
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

Django_project/core/urls.py
from django.urls import path
from core.views import index, about, car_details, add_car, update_car

app_name = 'core'

urlpatterns = [
    path('', index, name='index'),
    path('about/', about, name='about'),
    path('car_details/<int:car_pk>/', car_details, name='car_details'),
    path('add_car/', add_car, name='add_car'),
    path('update_car/<int:car_pk>/', update_car, name='update_car'),
]

Django_project/first_project/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('user/', include('user.urls', namespace='user')),
    path('api/', include('api.urls', namespace='api')),
    path('api-auth/', include('rest_framework.urls'))
]  + debug_toolbar_urls()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django_project/user/urls.py
from django.urls import path
from .views import UserRegisterView, UserLoginView, UserLogoutView, activate_account

app_name = 'user'

urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('activate/<int:uid>/<str:token>/', activate_account, name='activate'),
]

Django_project/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <div class="container mt-2">
        {% include 'navbar.html' %}
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %}">
                    {{ message }}
                </div>
            {% endfor %}
            <hr>
        {% endif %}
        {% block body %}
        {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

Django_project/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary mb-4">
  <div class="container-fluid">
    <div>
        <a href="{% url 'core:index' %}" style="margin-right: 20px">Home</a>
        <a href="{% url 'core:about' %}">About Us</a>
    </div>
    <div class="d-flex justify-content-between align-items-center">
            {% if user.is_authenticated %}
                <div class="d-flex justify-content-between align-items-center" style="width: 250px; margin-right: 20px">
                    hello, {{ user.username }} <small>visits: {{ visits }}</small>
                    <a href="{% url 'user:logout' %}">Logout</a>
                </div>
            {% else %}
                <div class="d-flex justify-content-between align-items-center" style="width: 150px; margin-right: 20px">
                    <a href="{% url 'user:login' %}">Log In</a>
                    <a href="{% url 'user:register' %}">Register</a>
                </div>
            {% endif %}
            <form class="d-flex" role="search" action="{% url 'core:index' %}">
                <input class="form-control me-2" type="search" placeholder="Search by make or model" name="q" value="{{ search_query }}" aria-label="Search">

                {% if category %}
                    <input type="hidden" name="category" value="{{ category }}">
                {% endif %}

                {% if year %}
                    <input type="hidden" name="year" value="{{ year }}">
                {% endif %}

                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
    </div>
  </div>
</nav>