Django_project/api/urls.py
from .views import (
    CategoryListView, CarListView, CarDetailView, CarCreateView, CarUpdateView, CarDeleteView,
    CarListCreateView, CarRetrieveUpdateDeleteView,
    CarViewSet
)
from rest_framework.routers import DefaultRouter
from django.urls import path, include

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)


router = DefaultRouter()

router.register('cars', CarViewSet, basename='cars')

app_name = 'api'

urlpatterns = [
    path('categories/', CategoryListView.as_view(), name='category_list'),
    # path('cars/', CarListView.as_view(), name='car_list'),
    # path('cars/create/', CarCreateView.as_view(), name='car_create'),
    # path('cars/<int:id>/', CarDetailView.as_view(), name='car_details'),
    # path('cars/update/<int:pk>/', CarUpdateView.as_view(), name='car_update'),
    # path('cars/delete/<int:pk>/', CarDeleteView.as_view(), name='car_delete'),
    # path('cars/', CarListCreateView.as_view(), name='car_list_create'),
    # path('cars/<int:pk>/', CarRetrieveUpdateDeleteView.as_view(), name='car_detail'),
    path('', include(router.urls)),
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

Django_project/core/urls.py
from django.urls import path
from core.views import index, about, car_details, add_car, update_car

app_name = 'core'

urlpatterns = [
    path('', index, name='index'),
    path('about/', about, name='about'),
    path('car_details/<int:car_pk>/', car_details, name='car_details'),
    path('add_car/', add_car, name='add_car'),
    path('update_car/<int:car_pk>/', update_car, name='update_car'),
]

Django_project/first_project/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('user/', include('user.urls', namespace='user')),
    path('api/', include('api.urls', namespace='api')),
    path('api-auth/', include('rest_framework.urls'))
]  + debug_toolbar_urls()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django_project/core/models.py
from django.db import models
from core.managers import BaseManager

class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)

    class Meta:
        db_table = 'category'
        verbose_name_plural = 'Category'

    def __str__(self):
        return self.name


class Car(models.Model):
    make = models.CharField(verbose_name="მწარმოებელი", max_length=15, null=False, blank=False)
    model = models.CharField(max_length=15, null=False, blank=False)
    description = models.TextField(blank=True)
    year = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    category = models.ForeignKey("core.Category", on_delete=models.SET_NULL, null=True, related_name='cars')
    is_sold = models.BooleanField(default=False)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=10000)
    quantity = models.IntegerField(default=1)
    image = models.ImageField(upload_to='car_images/', default='car_images/default.png')

    class Meta:
        db_table = "car"
        verbose_name_plural = "car"

    def __str__(self):
        return f"{self.make} {self.model}"

    objects = BaseManager()

Django_project/core/forms.py
from django import forms
from .models import Car


class CarForm(forms.ModelForm):

    class Meta:
        model = Car
        fields = "__all__"
        exclude = ('is_sold',)

Django_project/core/views.py
from django.db.models import Q
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from .models import Car, Category
from .forms import CarForm

def index(request):

    search_query = request.GET.get('q', '')
    category = request.GET.get('category', '')
    year = request.GET.get('year', '')
    max_year = request.GET.get('max_year', '')

    cars = Car.objects.all().select_related('category')

    if search_query:
        cars = cars.filter(Q(make__icontains=search_query) | Q(model__icontains=search_query))

    if category:
        cars = cars.filter(category_id=category)

    if year:
        cars = cars.filter(year__gte=year)

    if max_year:
        cars = cars.filter(year__lte=max_year)

    categories = Category.objects.all()

    return render(request, 'index.html', {
        'cars': cars,
        'categories': categories,
        'search_query': search_query,
        'category': category,
        'year': year,
        'max_year': max_year,
        'total_car': cars.count(),
    })

def about(request):

    return render(request, 'about.html')

def car_details(request, car_pk):

    car = get_object_or_404(Car, pk=car_pk)

    return render(request, 'car_detail.html', {'car': car})

def add_car(request):
    if request.method == 'POST':
        print(request.method)
        form = CarForm(request.POST, request.FILES)

        if form.is_valid():
            form.save()
            return redirect('core:index')
    else:
        form = CarForm()

    print(request.method)

    return render(request, 'add_car.html', {'form': form})

def update_car(request, car_pk):
    car = get_object_or_404(Car, pk=car_pk)

    if request.method == 'POST':
        form = CarForm(request.POST, request.FILES, instance=car)

        if form.is_valid():
            form.save()
            return redirect('core:car_details', car_pk=car.pk)

    else:
        form = CarForm(instance=car)

    return render(request, 'car_update.html', {'form': form})

Django_project/core/templates/about.html
{% extends 'base.html' %}

{% block title %} About page {% endblock %}

{% block body %}
    <h1>This is about page</h1>
    <hr>
    <a href="{% url 'core:index' %}">Home page</a>
{% endblock %}

Django_project/core/templates/add_car.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% load crispy_forms_filters %}

{% block title %}Add New Car{% endblock %}

{% block body %}
    <form action="." method="post" enctype="multipart/form-data"  style="width: 500px; margin: 20px auto">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Add</button>
    </form>
{%  endblock %}

Django_project/core/templates/car_detail.html
{% extends 'base.html' %}

{% block title %} Car Details {% endblock %}

{% block body %}

    <h2 style="text-align: center">{{ car.make }} - {{ car.model }}</h2>
    <hr>
    {% if car.image %}
        <div class="d-flex justify-content-center mb-5">
             <img src="{{ car.image.url }}" style="max-width: 400px" alt="car img">
        </div>
    {% endif %}
    <p>description: {{ car.description }}</p>
    <p>Publish year: {{ car.year }}</p>
    <span>Category: {{ car.category.name }}</span>
    <p>Price: {{ car.price }}</p>
    <p>Quantity: {{ car.quantity }}</p>
    <hr>
<a href="{% url 'core:index' %}">Home page</a>
    <hr>
    <a href="{% url 'core:update_car' car.pk %}">Update Car</a>

{% endblock %}

Django_project/core/templates/car_update.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% load crispy_forms_filters %}

{% block title %}Update car info{% endblock %}

{% block body %}
    <form action="." method="post" enctype="multipart/form-data" style="width: 500px; margin: 20px auto">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Update</button>
    </form>
{%  endblock %}

Django_project/core/templates/index.html
{% extends 'base.html' %}

{% block title %} Home Page {% endblock %}

{% block body %}
    <div class="row">
        <div class="col-lg-3">
                <h2>Filters</h2>
                <form action="" class="border border-info p-4 rounded">
                    <select class="form-select mb-3" name="category">
                        <option value="">All Categories</option>
                        {% for cat in categories %}
                            <option value="{{ cat.id }}" {% if category == cat.id|stringformat:'s' %}selected{% endif %}>
                                {{ cat }}
                            </option>
                        {% endfor %}
                    </select>

                    {% if search_query %}
                        <input type="hidden" name="q" value="{{ search_query }}">
                    {% endif %}

                    <input class="form-control mb-2" type="number" name="year" placeholder="minimum year" value="{{ year }}">
                    <input class="form-control mb-3" type="number" name="max_year" placeholder="maximum year" value="{{ max_year }}">

                    <button class="btn btn-info rounded-pill px-4" style="color: white" type="submit">Filter</button>
                </form>
        </div>
        <div class="col-lg-9">
            <div class="d-flex">
                <h2 style="margin-right: 100px">Car List({{ total_car }})</h2>
                <a class="btn btn-primary" href="{% url 'core:add_car' %}" style="margin-right: 50px">Add New Car</a>
            </div>
            <div class="row justify-content-between g-4">
                {% for car in cars %}
                <div class="card" style="width: 16rem;">
                  {% if car.image %}
                      <img src="{{ car.image.url }}" class="card-img-top" style="height: 200px; width: 200px; margin: auto" alt="...">
                  {% endif %}
                  <div class="card-body">
                    <h5 class="card-title">{{ car.make }} {{ car.model }}</h5>
                    <p class="card-text">{{ car.description|truncatechars:50 }}</p>
                    <a href="{% url 'core:car_details' car.pk %}" class="btn btn-primary">See full info</a>
                  </div>
                </div>
            {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}